name: fail
version: "0.777"
summary: The most important snap of the snap universe
description: |
  This snap will be THE snap that will change everything
parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
